/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/measure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Measure front-of-card centering
         * @description Upload a front-of-card JPEG, PNG, or WEBP image and receive a front centering measurement, PSA centering ceiling, overlay coordinates, and processing metadata. Phase 1 returns a deterministic mock measurement keyed from an in-memory hash of the uploaded file bytes.
         *     Image bytes are streamed, hashed in memory, and discarded before the handler returns. Bytes are never persisted to disk or logged.
         */
        post: operations["measureCardCentering"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @description Service health status.
             * @enum {string}
             */
            status: "ok";
        };
        MeasureRequest: {
            /**
             * Format: binary
             * @description JPEG, PNG, or WEBP image file. Maximum size is 20 MB.
             */
            file: string;
        };
        MeasurementResponse: {
            image: components["schemas"]["ImageMetadata"];
            centering: components["schemas"]["CenteringMeasurement"];
            psa: components["schemas"]["PsaAssessment"];
            overlay: components["schemas"]["MeasurementOverlay"];
            pipeline: components["schemas"]["PipelineInfo"];
            metadata: components["schemas"]["ProcessingMetadata"];
        };
        ImageMetadata: {
            /**
             * @description Validated media type of the uploaded image.
             * @enum {string}
             */
            contentType: "image/jpeg" | "image/png" | "image/webp";
            /** @description Uploaded image width in pixels. */
            widthPx: number;
            /** @description Uploaded image height in pixels. */
            heightPx: number;
        };
        CenteringMeasurement: {
            leftRight: components["schemas"]["LeftRightRatio"];
            topBottom: components["schemas"]["TopBottomRatio"];
            /**
             * @description Axis with the larger major-side centering percentage.
             * @enum {string}
             */
            worstAxis: "leftRight" | "topBottom";
            /** @description Larger side percentage on the worst axis, used for PSA ceiling lookup. */
            worstAxisMaxPercent: number;
        };
        LeftRightRatio: {
            /** @description Left-side share of the horizontal centering ratio. */
            leftPercent: number;
            /** @description Right-side share of the horizontal centering ratio. */
            rightPercent: number;
        };
        TopBottomRatio: {
            /** @description Top-side share of the vertical centering ratio. */
            topPercent: number;
            /** @description Bottom-side share of the vertical centering ratio. */
            bottomPercent: number;
        };
        PsaAssessment: {
            /**
             * @description Centering-only PSA ceiling based on the worst axis.
             * @enum {string}
             */
            ceiling: "PSA_10" | "PSA_9" | "PSA_8" | "PSA_7" | "BELOW_PSA_7";
            /** @description Human-readable PSA centering ceiling label. */
            label: string;
            /** @description Server-echoed PSA centering threshold rows for client rendering. */
            thresholds: components["schemas"]["PsaThreshold"][];
        };
        PsaThreshold: {
            /**
             * @description PSA threshold row represented by this limit.
             * @enum {string}
             */
            ceiling: "PSA_10" | "PSA_9" | "PSA_8" | "PSA_7";
            /** @description Human-readable PSA threshold label. */
            label: string;
            /**
             * @description Maximum allowed major-side percentage for this PSA centering threshold.
             * @enum {number}
             */
            maxMajorPercent: 55 | 60 | 65 | 70;
            /**
             * @description Human-readable ratio label for this threshold.
             * @enum {string}
             */
            ratioLabel: "55/45" | "60/40" | "65/35" | "70/30";
        };
        MeasurementOverlay: {
            /**
             * @description Rectangles and gaps are measured in the uploaded image pixel space.
             * @enum {string}
             */
            coordinateSpace: "imagePixels";
            outerCard: components["schemas"]["Rect"];
            innerFrame: components["schemas"]["Rect"];
            gaps: components["schemas"]["GapMeasurements"];
        };
        Rect: {
            /** @description Left coordinate in pixels. */
            x: number;
            /** @description Top coordinate in pixels. */
            y: number;
            /** @description Rectangle width in pixels. */
            width: number;
            /** @description Rectangle height in pixels. */
            height: number;
        };
        GapMeasurements: {
            /** @description Pixel gap between outer card and inner frame on the left side. */
            leftPx: number;
            /** @description Pixel gap between outer card and inner frame on the right side. */
            rightPx: number;
            /** @description Pixel gap between outer card and inner frame on the top side. */
            topPx: number;
            /** @description Pixel gap between outer card and inner frame on the bottom side. */
            bottomPx: number;
        };
        PipelineInfo: {
            /**
             * @description Measurement pipeline used for this response.
             * @enum {string}
             */
            mode: "mock" | "opencv";
            /** @description Version of the measurement pipeline contract or implementation. */
            version: string;
        };
        ProcessingMetadata: {
            /** @description Server-side processing duration in milliseconds. */
            processingMs: number;
            /** @description Non-fatal processing warnings safe to show or log. */
            warnings: string[];
        };
        ErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
        ApiError: {
            /**
             * @description Machine-readable error code.
             * @enum {string}
             */
            code: "INVALID_UPLOAD" | "FILE_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "IMAGE_UNREADABLE" | "CARD_NOT_DETECTED" | "MEASUREMENT_FAILED";
            /** @description Human-readable error message safe to return to clients. */
            message: string;
            /** @description Error metadata safe for support and log correlation. */
            details: {
                /**
                 * Format: uuid
                 * @description Request-scoped UUID metadata only; it is not derived from image bytes.
                 */
                requestId: string;
            } & {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    measureCardCentering: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["MeasureRequest"];
            };
        };
        responses: {
            /** @description Front centering measurement completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementResponse"];
                };
            };
            /** @description The upload request is malformed or missing the file field. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The uploaded file exceeds the 20 MB limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The uploaded file content type is not JPEG, PNG, or WEBP. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image was accepted but could not be interpreted or measured. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The measurement pipeline failed unexpectedly. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
